# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-22 02:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drink',
            name='instructions',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='drink',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
